[build]
builder = "NIXPACKS"

[variables]
PORT = "5000"

[deploy]
startCommand = "npx prisma generate --schema=./server/prisma/schema.prisma && npx prisma db push --schema=./server/prisma/schema.prisma --accept-data-loss && node server/index.js"
healthcheckPath = "/"
healthcheckTimeout = 300
